# This actions workflow will run when there is:
# 1- a new Pull Request against main branch;
# 2- a new Push to the main branch;
#
# Basically, it deploys a new postgres service, and 
# runs some steps that set up Elixir and Phoenix, 
# and run the Benefits tests.

name: Backend CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    name: Build and test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: benefits_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    
    env:
      MIX_ENV: test
      SECRET_KEY_BASE: ${{ secrets.SECRET_KEY_BASE }}

